### PR TITLE
Add debounce option

### PR DESCRIPTION
**Pull request by kuon**
Implementation of #2

### CODE REVIEW

**Comment by aj-foster** [comment]
Hi @kuon 👋🏼 

Thank you for taking the time to raise this issue and write a solution! And thanks also for your patience during my travel.

I'm going to push a few changes to what you have (explained below), but the overall flow should be the same as you had it. Here's my thinking that led to the changes:

1. I'm interested in making `debounce` configurable on a per-profile basis. For the network mount example you gave, this unfortunately means you'll need to repeat the `debounce` option for each profile. However, this may be beneficial if the root cause of the multiple writes is something else. For example, one of my projects has an asset compiler that (annoyingly) ends up writing the asset files twice. It would be nice to debounce these files while leaving the rest alone.

2. The `Executor` module you wrote is nice in the way it separates the debounce logic into a separate place. However, I wanted to see if we could implement it within the same watcher process. This unfortunately makes the code a bit more messy (it's not a nice, clean GenServer like yours). It's one less process to manage, though, and there's potentially less risk of issues in the future between the watcher and the executor.

With all of that said, I leaned on your contribution heavily to make sure I understood the goal and what the solution should look like. Thank you for taking the time to write it.

I'll leave it here in the PR for a little while before merging everything. If you have any thoughts on my changes, I'm all ears.

**Comment by kuon** [comment]
I agree with the debounce option per profile. But I disagree with removing the genserver. Elixir processes are really lightweight, and I don't think there is any significant cost in keeping it this way. Simpler code is more important, especially as this is a dev tool, and not some performance critical part where we would be chasing usec. That being said, if you find an elegant way to rewrite it then great :) 

Cheers

-- 

Nicolas Goy
https://www.kuon.ch




-------- Original Message --------

**Comment by kuon** [comment]
Hello, do you intend to merge this or do you want me to make more changed?

**Comment by aj-foster** [comment]
Thank you for your contribution! I will prepare a release shortly.

**Comment by aj-foster** [comment]
Released as [0.1.2](https://hex.pm/packages/phoenix_copy/0.1.2).

**Pull request merged**
